In [1]:
import numpy as np

In [23]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print(arr.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [ ]:
# array_name[first two row, first two column]
arr[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [32]:
# array_name[last two row, last two column]
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])